name: Test setup-bonsai
on:
  push:
  workflow_dispatch:
env:
  NODE_OPTIONS: --enable-source-maps --trace-uncaught
jobs:
  run:
    name: Test setup-bonsai
    runs-on: ubuntu-latest
    steps:
      - uses: NgrDavid/setup-bonsai@main
        with:
          environment-path: |
            one
            two
